# Generated by Django 4.1 on 2023-09-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='b_id',
            new_name='board',
        ),
    ]
