CREATE DATABASE MyNews;
use MyNews;

CREATE TABLE t_writer(
	w_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    w_name VARCHAR(10) NOT NULL
);

CREATE TABLE t_news(
	n_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    n_title VARCHAR(255) NOT NULL,
    n_content TEXT NOT NULL,
    w_id SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (w_id) REFERENCES t_writer (w_id)
);


CREATE TABLE t_user(
	u_id SMALLINT UNSIGNED NOT NULL  AUTO_INCREMENT PRIMARY KEY,
    u_name VARCHAR(10) NOT NULL,
    u_pw  VARCHAR(255) NOT NULL,
    u_nickname VARCHAR(10)
);

CREATE TABLE t_newsComment(
	c_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    c_content VARCHAR(255) NOT NULL,
    u_id SMALLINT UNSIGNED NOT NULL,
    n_id SMALLINT UNSIGNED NOT NULL,
    depth SMALLINT UNSIGNED NOT NULL,
    parent_content SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (u_id) REFERENCES t_user (u_id),
    FOREIGN KEY (n_id) REFERENCES t_news (n_id),
    FOREIGN KEY (parent_content) REFERENCES t_newsComment (c_id)        
);

CREATE TABLE t_commentLike(
	c_id SMALLINT UNSIGNED NOT NULL,
    u_id SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (u_id) REFERENCES t_user (u_id),
    FOREIGN KEY (c_id) REFERENCES t_newsComment (c_id)
);

CREATE TABLE t_emotion(
	em_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    emotion VARCHAR(255) NOT NULL
);

CREATE TABLE t_newsEmotion(
	ne_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    n_id SMALLINT UNSIGNED NOT NULL,
    u_id SMALLINT UNSIGNED NOT NULL,
    em_id SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (n_id) REFERENCES t_news (n_id),
    FOREIGN KEY (u_id) REFERENCES t_user (u_id),
    FOREIGN KEY (em_id) REFERENCES t_emotion (em_id)
);
