# Generated by Django 4.1 on 2023-10-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
